/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface IntegersInterface extends Interface {
  functions: {
    parseInt: TypedFunctionDescription<{ encode([_value]: [string]): string }>;

    toByte: TypedFunctionDescription<{
      encode([_base]: [BigNumberish]): string;
    }>;
  };

  events: {};
}

export class Integers extends Contract {
  connect(signerOrProvider: Signer | Provider | string): Integers;
  attach(addressOrName: string): Integers;
  deployed(): Promise<Integers>;

  on(event: EventFilter | string, listener: Listener): Integers;
  once(event: EventFilter | string, listener: Listener): Integers;
  addListener(eventName: EventFilter | string, listener: Listener): Integers;
  removeAllListeners(eventName: EventFilter | string): Integers;
  removeListener(eventName: any, listener: Listener): Integers;

  interface: IntegersInterface;

  functions: {
    parseInt(_value: string): Promise<BigNumber>;

    toByte(_base: BigNumberish): Promise<string>;
  };

  parseInt(_value: string): Promise<BigNumber>;

  toByte(_base: BigNumberish): Promise<string>;

  filters: {};

  estimate: {
    parseInt(_value: string): Promise<BigNumber>;

    toByte(_base: BigNumberish): Promise<BigNumber>;
  };
}
